In [1]:
import os
from dotenv import load_dotenv
from synthetic.synthetic_data import SyntheticData
from llms.openai import OpenAI
from prompt import DataFromPrompt
from prompt.data_generation_prompt import DataGenerationPrompt 
# Load environment variables
load_dotenv()
INDOX_API_KEY = os.getenv("INDOX_API_KEY")

user_prompt = "Generate a dataset with 3 column and 3 row about astronomy."

with SyntheticData("./output"):
    gpt_4 = OpenAI(api_key=INDOX_API_KEY, model_name="gpt-4o-mini")

    instruction = DataGenerationPrompt.get_instruction(user_prompt)

    dataset = DataFromPrompt(
        prompt_name="Generate Research Paper Abstracts",
        args={
            "llm": gpt_4,
            "n": 1,
            "temperature": 0.1,
            "instruction": instruction,
        },
        outputs={"generations": "generate"},
    )
    df=dataset.run()
    print(df)

Output directory './output' is ready.
Generated Data in dictionary format: [{'Celestial_Object': ['Quasar', 'Neutron Star', 'Brown Dwarf'], 'Distance_Light_Years': [12000, 4500, 250], 'Discovery_Year': [1985, 1967, 1995]}]
  Celestial_Object  Distance_Light_Years  Discovery_Year
0           Quasar                 12000            1985
1     Neutron Star                  4500            1967
2      Brown Dwarf                   250            1995
Exiting synthetic data context. Cleaning up if needed.

In [2]:
df

  Celestial_Object  Distance_Light_Years  Discovery_Year
0           Quasar                 12000            1985
1     Neutron Star                  4500            1967
2      Brown Dwarf                   250            1995

In [1]:
import os
from dotenv import load_dotenv
from synthetic.synthetic_data import SyntheticData
from llms.openai import OpenAI
from prompt import DataFromPrompt
from prompt.data_generation_prompt import DataGenerationPrompt 
from upload_data import load_data

load_dotenv()
INDOX_API_KEY = os.getenv("INDOX_API_KEY")

dataset_file_path = "generated_astronomy_dataset.xlsx"

df = load_data(dataset_file_path)

user_prompt = " generate one row."
with SyntheticData("./output"):
    # Load GPT-4
    gpt_4 = OpenAI(api_key=INDOX_API_KEY, model_name="gpt-4o-mini")

    instruction = DataGenerationPrompt.get_instruction(user_prompt)

    dataset = DataFromPrompt(
        prompt_name="Generate New Column",
        args={
            "llm": gpt_4,
            "n": 1,
            "temperature": 0.1,
            "instruction": instruction,
        },
        outputs={"generations": "generate"},
        dataframe=df 
    )
    updated_df = dataset.run()
    print(updated_df)

Output directory './output' is ready.
Generated Data in dictionary format: [{'0': ['Celestial Body', 'Diameter (km)', 'Distance from Sun (million km)'], '1': ['Venus', 12104, 108.2]}]
                                0      1
0                  Celestial Body  Venus
1                   Diameter (km)  12104
2  Distance from Sun (million km)  108.2
Exiting synthetic data context. Cleaning up if needed.

In [3]:
syn=SyntheticData("./output")
syn.save_data(data=df,filename="test")

Data saved to './output\test.xlsx' as Excel.

In [2]:
import os
from dotenv import load_dotenv
from llms.openai import OpenAI
from prompt import FewShotPrompt  

load_dotenv()
INDOX_API_KEY = os.getenv("INDOX_API_KEY")

examples = [
    {
        "input": "Generate a dataset with 3 columns and 2 rows about biology.",
        "output": '[{"Species": "Human", "Cell Count": 37.2, "Age": 30}, {"Species": "Mouse", "Cell Count": 3.2, "Age": 2}]'
    },
    {
        "input": "Generate a dataset with 3 columns and 2 rows about chemistry.",
        "output": '[{"Element": "Hydrogen", "Atomic Number": 1, "Weight": 1.008}, {"Element": "Oxygen", "Atomic Number": 8, "Weight": 15.999}]'
    }
]

user_prompt = "Generate a dataset with 3 columns and 2 rows about astronomy."

gpt_4 = OpenAI(api_key=INDOX_API_KEY, model_name="gpt-4o-mini")

dataset = FewShotPrompt(
    prompt_name="Generate Astronomy Dataset",
    args={
        "llm": gpt_4,
        "n": 1,  
        "instruction": user_prompt,  
    },
    outputs={"generations": "generate"},
    examples=examples  
)

df = dataset.run()

print(df)
df.to_excel("generated_astronomy_dataset.xlsx", index=False)

Generated Data in dictionary format: [[{'Celestial Body': 'Earth', 'Diameter (km)': 12742, 'Distance from Sun (AU)': 1}, {'Celestial Body': 'Mars', 'Diameter (km)': 6779, 'Distance from Sun (AU)': 1.52}]]
  Celestial Body  Diameter (km)  Distance from Sun (AU)
0          Earth          12742                    1.00
1           Mars           6779                    1.52

In [3]:
df

  Celestial Body  Diameter (km)  Distance from Sun (AU)
0          Earth          12742                    1.00
1           Mars           6779                    1.52